name: denkwerk/mosparo-form
label: denkwerk - mosparo integration for EXT:form and Extbase-based forms
settings:
  plugin:
      tx_mosparoform:
          settings:
              defaultProject: default
