services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Denkwerk\MosparoForm\:
        resource: '../Classes/*'
        exclude: '../Classes/Domain/Model/*'

    Denkwerk\MosparoForm\Validation\Validator\MosparoCaptchaValidator:
        public: true

    Denkwerk\MosparoForm\FormNormalizer\FormNormalizer:
        tags:
            - { name: 'mosparo.form_normalizer' }

    Denkwerk\MosparoForm\FormNormalizer\ExtbaseNormalizer:
        tags:
            - { name: 'mosparo.form_normalizer', priority: -100 }

    Denkwerk\MosparoForm\FormNormalizer\FormNormalizerManager:
        arguments:
            $normalizers: !tagged_iterator mosparo.form_normalizer

